package database

import "github.com/shuldan/framework/pkg/errors"

var newDatabaseCode = errors.WithPrefix("DATABASE")

var (
	ErrConfigNotFound                      = newDatabaseCode().New("database configuration not found")
	ErrConnectionsNotFound                 = newDatabaseCode().New("database connections configuration not found")
	ErrCreateConnection                    = newDatabaseCode().New("failed to create connection {{.name}}: {{.reason}}")
	ErrRegisterConnection                  = newDatabaseCode().New("failed to register connection {{.name}}: {{.reason}}")
	ErrResolveConfig                       = newDatabaseCode().New("failed to resolve dbDonfig: {{.reason}}")
	ErrResolveConnections                  = newDatabaseCode().New("failed to resolve database connections: {{.reason}}")
	ErrConnectDatabase                     = newDatabaseCode().New("failed to connect to database {{.name}}: {{.reason}}")
	ErrCloseDatabase                       = newDatabaseCode().New("failed to close database {{.name}}: {{.reason}}")
	ErrDriverNotSpecified                  = newDatabaseCode().New("driver not specified for connection {{.name}}")
	ErrDSNNotSpecified                     = newDatabaseCode().New("dsn not specified for connection {{.name}}")
	ErrConnectionNotFound                  = newDatabaseCode().New("database connection '{{.name}}' not found")
	ErrInvalidConnectionType               = newDatabaseCode().New("invalid database connection type for '{{.name}}'")
	ErrInvalidDatabaseType                 = newDatabaseCode().New("invalid database type for repository")
	ErrMultipleCloseErrors                 = newDatabaseCode().New("errors closing databases")
	ErrEntityNotFound                      = newDatabaseCode().New("entity not found with id {{.id}}")
	ErrInvalidID                           = newDatabaseCode().New("invalid ID: {{.id}}")
	ErrInvalidCriteria                     = newDatabaseCode().New("invalid search criteria: {{.reason}}")
	ErrFailedToOpenDatabase                = newDatabaseCode().New("failed to open database")
	ErrDatabaseNotConnected                = newDatabaseCode().New("database not connected")
	ErrTransactionFailed                   = newDatabaseCode().New("transaction failed: {{.reason}}")
	ErrMigrationFailed                     = newDatabaseCode().New("migration {{.id}} failed: {{.reason}}")
	ErrRepositoryNotInitialized            = newDatabaseCode().New("repository not properly initialized")
	ErrInvalidIDType                       = newDatabaseCode().New("invalid ID type: expected {{.expected}}, got {{.actual}}")
	ErrFailedToCreateSchemaMigrationsTable = newDatabaseCode().New("failed to create schema_migrations table")
	ErrFailedToCreateSchemaMigrationsIndex = newDatabaseCode().New("failed to create schema_migrations index")
	ErrFailedToGetAppliedMigrations        = newDatabaseCode().New("failed to get applied migrations")
	ErrFailedToBeginTransaction            = newDatabaseCode().New("failed to begin transaction")
	ErrNoMigrationsToRollback              = newDatabaseCode().New("no migrations to rollback")
	ErrFailedToExecuteQuery                = newDatabaseCode().New("failed to execute query: {{.query}}")
)
